Added support for deleting individual documents by id
SumoLogic/elasticsearch-client pull request #109
Opened 2017-03-21 01:38 UTC by pnzrdrgoon

Please let me know if you have any concerns with the code.

2017-03-22 19:42 UTC, rcoh requested changes
Couple of changes to the tests

2017-03-22 19:42 UTC, rcoh commented on elasticsearch-core/src/test/scala/com/sumologic/elasticsearch/restlastic/RestlasticSearchClientTest.scala
> +      whenReady(resFut){res =>
when ready returns the result of the function. You can do:
```
val foundDoc: ElasticJsonDocument = whenReady(resFut) { res =>
  res.raw.....
}
```

This also simplifies the subsequent code.

2017-03-22 19:42 UTC, rcoh commented on elasticsearch-core/src/test/scala/com/sumologic/elasticsearch/restlastic/RestlasticSearchClientTest.scala
> +        e shouldBe a [ElasticErrorResponse]
```
e match {
  case e: ElasticErrorResponse => ...
  case other => fail(s"Error expected, got ${other}")
}

2017-03-22 19:42 UTC, rcoh commented on elasticsearch-core/src/test/scala/com/sumologic/elasticsearch/restlastic/RestlasticSearchClientTest.scala
> +      whenReady(resFut){res =>
Another option, ```resFut.futureValue.rawSearch......```

2017-03-22 22:22 UTC, agearhart reviewed
Please let me know if I misunderstood the alteration suggestions.  Thank you for the help!

2017-03-23 16:26 UTC, rcoh approved these changes

2017-03-27 20:31 UTC, merged

2017-03-27 20:45 UTC, CCheSumo commented
@pnzrdrgoon Let me know if you need a new branch cut that includes the recent PRs for delete/bulkDelete with document id(s)?

2017-03-27 22:32 UTC, pnzrdrgoon commented
That would be fantastic if possible.  I've built a jar locally for use, but
new version cut would be great!

On Mon, Mar 27, 2017 at 1:45 PM, Chuck Che <notifications@github.com> wrote:

> @pnzrdrgoon <https://github.com/pnzrdrgoon> Let me know if you need a new
> branch cut that includes the recent PRs for delete/bulkDelete with document
> id(s)?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/SumoLogic/elasticsearch-client/pull/109#issuecomment-289580604>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACY1tOBYYhFabc5zYLf4iMpAbF-an-qmks5rqB_-gaJpZM4MjOda>
> .
>

2017-03-28 00:22 UTC, CCheSumo commented
@pnzrdrgoon release cut 1.0.30 contains all your changes.