Swap out spray for Akka http
SumoLogic/elasticsearch-client pull request #111
Opened 2017-04-18 06:04 UTC by seanpquig

2017-04-18 06:20 UTC, rcoh commented
Thanks for this long needed change! It's not building on CI for some reason -- I assume it builds for you locally?

2017-04-18 06:34 UTC, seanpquig commented
It does build, and all tests run for me locally @rcoh.  However, I'm using Java 8.  I can revert to Akka versions that still support Java 7?  Unless there are plans to migrate to Java 8 for the project?

2017-04-18 17:25 UTC, rcoh requested changes

2017-04-18 17:25 UTC, rcoh commented on elasticsearch-aws/src/main/scala/com/sumologic/elasticsearch/util/AwsRequestSigner.scala
> +    val data = Await.result(dataFuture, 1.second)
what precisely is being waited for here? Are we waiting for the request to finish or is it just for some sort of string conversion?

2017-04-18 17:25 UTC, rcoh commented on elasticsearch-core/src/main/scala/com/sumologic/elasticsearch/restlastic/RestlasticSearchClient.scala
> +        val entityString = Await.result(entityFuture, 100.millis)
Maybe cleaner to use `.recover` or `.recoverWith` to handle the failure without having to Await on the entity?

2017-04-18 17:25 UTC, rcoh commented on elasticsearch-core/src/main/scala/com/sumologic/elasticsearch/util/AkkaHttpUtil.scala
> +    entity.toStrict(streamTimeout).map(_.data.utf8String)
I would prefer doing the `Await` here -- we wait for seemingly arbitrary amounts of time for this in other places. I'd rather standardize in one place even if it makes the API a little less flexible. Does this only return a future as a semantic side effect of akka-http or is there really something that we're waiting for?

2017-04-18 17:57 UTC, CCheSumo commented
@rcoh Regarding the java version, I have seen two PRs having problem with java 7. As a matter of fact, our infrastructure is also moving to java 8. What do you think about we upgrade the scala/akka version? I will create a PR if that sounds reasonable.

2017-04-18 17:59 UTC, seanpquig commented on elasticsearch-aws/src/main/scala/com/sumologic/elasticsearch/util/AwsRequestSigner.scala
> +    val data = Await.result(dataFuture, 1.second)
This is an artifact of all Akka HTTP request/response entities being modeled as streams, so in this instance the full payload string is being pulled from that stream abstraction.  It does not involve an HTTP request/network call.

More on streaming nature of entities: http://doc.akka.io/docs/akka-http/current/scala/http/implications-of-streaming-http-entity.html#implications-of-streaming-http-entities

2017-04-18 17:59 UTC, seanpquig commented on elasticsearch-core/src/main/scala/com/sumologic/elasticsearch/restlastic/RestlasticSearchClient.scala
> +        val entityString = Await.result(entityFuture, 100.millis)
I'll try that 👍

2017-04-18 18:03 UTC, seanpquig commented on elasticsearch-core/src/main/scala/com/sumologic/elasticsearch/util/AkkaHttpUtil.scala
> +    entity.toStrict(streamTimeout).map(_.data.utf8String)
This future is a side effect of Akka HTTP modeling entities as streams.  I'll try refactor to better consolidate necessary waiting, and think through all the implications.

2017-04-20 03:37 UTC, rcoh commented
@CCheSumo upgrading the scala/java version is fine with me

2017-04-20 03:37 UTC, rcoh approved these changes

2017-04-20 15:58 UTC, seanpquig commented
How do you guys want to coordinate Java 8 switch with Akka versions in this PR?  Java 8 would enable these changes to use stable Akka HTTP and not the old experimental jar.

2017-04-20 17:37 UTC, merged

2017-04-20 17:38 UTC, CCheSumo commented
@seanpquig let's keep the changes in this PR. After Java 8 is enabled, we have serval libs we will upgrade, the akka core included.

2017-04-20 23:31 UTC, seanpquig commented
Sounds good @CCheSumo.  Thanks.