Added option for uriQuery in query method
SumoLogic/elasticsearch-client pull request #88
Opened 2016-11-23 14:17 UTC by TomLous

I wanted to supply preference information into the rest query
The runEsCommand allowed for this, but the parameter was not implemented in the overal query call

See:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-preference.html

2016-11-23 22:33 UTC, rcoh requested changes
Please revert the pom changes

2016-11-23 22:33 UTC, rcoh commented on elasticsearch-core/src/main/scala/com/sumologic/elasticsearch/restlastic/RestlasticSearchClient.scala
> +    runEsCommand(query, s"/${index.name}/${tpe.name}/_search", query=uriQuery).map { rawJson =>
Space around `=`

2016-11-28 09:20 UTC, TomLous commented
I'm sorry the last commit should not be part of the pull request (I'm new at this)
How can I remove this from it?

2016-11-28 17:12 UTC, rcoh commented
Probably easiest is to run
```
git revert 221b2d64f2a12cfbab011bfd966afd1ff2c9694b
git push
```

You can also rebase to remove it but that's a bit more complex.

2016-11-29 09:50 UTC, TomLous commented
'fixed' it. Sorry for the mess.

2016-11-29 20:24 UTC, rcoh approved these changes

2016-11-29 20:24 UTC, rcoh commented
Thanks for your contribution!

2016-11-29 20:24 UTC, merged